
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'LPAREN NUMBER PLUS RPAREN TIMESexpr : expr PLUS term\n| termterm : term TIMES factor\n| factorfactor : NUMBER\n| LPAREN expr RPAREN'
    
_lr_action_items = {'NUMBER':([0,5,6,7,],[4,4,4,4,]),'LPAREN':([0,5,6,7,],[5,5,5,5,]),'$end':([1,2,3,4,9,10,11,],[0,-2,-4,-5,-1,-3,-6,]),'PLUS':([1,2,3,4,8,9,10,11,],[6,-2,-4,-5,6,-1,-3,-6,]),'RPAREN':([2,3,4,8,9,10,11,],[-2,-4,-5,11,-1,-3,-6,]),'TIMES':([2,3,4,9,10,11,],[7,-4,-5,7,-3,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,5,],[1,8,]),'term':([0,5,6,],[2,2,9,]),'factor':([0,5,6,7,],[3,3,3,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> expr PLUS term','expr',3,'p_expr','exp7.py',24),
  ('expr -> term','expr',1,'p_expr','exp7.py',25),
  ('term -> term TIMES factor','term',3,'p_term','exp7.py',29),
  ('term -> factor','term',1,'p_term','exp7.py',30),
  ('factor -> NUMBER','factor',1,'p_factor','exp7.py',34),
  ('factor -> LPAREN expr RPAREN','factor',3,'p_factor','exp7.py',35),
]
