
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'MUL NUM PLUSe : e PLUS te : tt : t MUL NUMt : NUM'
    
_lr_action_items = {'NUM':([0,4,5,],[3,3,7,]),'$end':([1,2,3,6,7,],[0,-2,-4,-1,-3,]),'PLUS':([1,2,3,6,7,],[4,-2,-4,-1,-3,]),'MUL':([2,3,6,7,],[5,-4,5,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'e':([0,],[1,]),'t':([0,4,],[2,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> e","S'",1,None,None,None),
  ('e -> e PLUS t','e',3,'p_e_plus','one.py',605),
  ('e -> t','e',1,'p_e_t','one.py',609),
  ('t -> t MUL NUM','t',3,'p_t_mul','one.py',613),
  ('t -> NUM','t',1,'p_t_num','one.py',617),
]
